[build]
  publish = "dist"
  command = "astro build"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "16"


[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"