name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    name: Deploy
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        env:
          FAUNA_GRAPHQL_HOST: ${{ secrets.FAUNA_GRAPHQL_HOST }}
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
          IMAGEKIT_ID: ${{ secrets.IMAGEKIT_ID }}
        run: yarn build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            Deploy from GitHub Actions
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-commment: true
